import globals from 'globals';
import pluginJs from '@eslint/js';
import prettierPlugin from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';

const gameGlobals = {
    GAME_WIDTH: true,
    GAME_HEIGHT: true,
    TARGET_FPS: true,
    FRAME_TIME: true,
    DELTA_TIME_MAX: true,
    COLORS: true,
    ROOM_TYPES: true,
    CHEST_TYPES: true,
    WEAPONS: true,
    ENEMIES: true,
    SKILLS: true,
    PASSIVES: true,
    DECORATIONS: true,
    LEVELS: true,
    TRAPS: true,
    SOUNDS: true,
    PARTICLES: true,
    BULLETS: true,
    ITEMS: true,
    POTIONS: true,
    RELICS: true,
    ACHIEVEMENTS: true,
    GAME_STATES: true,
    CHARACTERS: true,
    EVENTS: true,
    DIFFICULTY: true,
    CHARACTER_CLASSES: true,
    PIXEL_SIZE: true,
    AUDIO: true,
    ConfigLoader: true,
    Item: true,
    Inventory: true,
    Shop: true,
    Achievement: true,
    Camera: true,
    GameStateManager: true,
    InputManager: true,
    Renderer: true,
    SaveManager: true,
    Settings: true,
    Leaderboard: true,
    SoundManager: true,
    Tutorial: true,
    UI: true,
    AudioManager: true,
    Particle: true,
    Bullet: true,
    Weapon: true,
    WeaponPistol: true,
    WeaponLightning: true,
    WeaponGrenade: true,
    WeaponFlame: true,
    WeaponBoomerang: true,
    WeaponFreeze: true,
    WeaponShotgun: true,
    WeaponHoming: true,
    LightningBullet: true,
    GrenadeBullet: true,
    FlameBullet: true,
    BoomerangBullet: true,
    FreezeBullet: true,
    ShotgunBullet: true,
    HomingBullet: true,
    Player: true,
    Passive: true,
    Skill: true,
    Character: true,
    Enemy: true,
    EnemySlime: true,
    EnemyBat: true,
    EnemyGhost: true,
    Boss: true,
    Trap: true,
    Chest: true,
    RoomNode: true,
    Corridor: true,
    DungeonLevel: true,
    DungeonGenerator: true,
    Room: true,
    RoomRenderer: true,
    DoorManager: true,
    Minimap: true,
    EventBus: true,
    SaveSystem: true,
    SaveMenu: true,
    InputSystem: true,
    CollisionSystem: true,
    DamageSystem: true,
    DropSystem: true,
    AchievementSystem: true,
    RoomManager: true,
    BulletManager: true,
    ParticleManager: true,
    Game: true,
    CharacterSelect: true,
    game: true,
    gameState: true,
    inputManager: true,
    renderer: true,
    camera: true,
    soundManager: true,
    saveManager: true,
    ui: true,
    CANVAS_SCALE: true,
    ASSETS: true,
    DIRECTIONS: true,
    STATS: true,
    MODIFIERS: true,
    EFFECTS: true,
    STATUS_EFFECTS: true,
    PROJECTILE_TYPES: true,
    DAMAGE_TYPES: true,
    LOOT_TABLES: true,
    SPAWN_RULES: true,
    ROOM_TEMPLATES: true,
    DIALOGUES: true,
    TUTORIAL_STEPS: true,
    SETTINGS_DEFAULTS: true,
    LEADERBOARD_CONFIG: true,
    SAVE_VERSION: true,
    COMPATIBILITY: true,
    DEBUG: true,
    PROFILE: true,
    PERF_MONITOR: true
};

export default [
    {
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.es2021,
                ...globals.node,
                ...gameGlobals
            },
            ecmaVersion: 'latest',
            sourceType: 'module'
        }
    },
    pluginJs.configs.recommended,
    prettierConfig,
    {
        plugins: {
            prettier: prettierPlugin
        },
        rules: {
            'prettier/prettier': 'error',
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-debugger': 'error',
            eqeqeq: ['error', 'always'],
            curly: ['error', 'all'],
            quotes: ['error', 'single'],
            semi: ['error', 'always'],
            indent: ['error', 4, { SwitchCase: 1 }],
            'max-len': ['warn', { code: 120, ignoreStrings: true, ignoreTemplateLiterals: true }],
            'no-trailing-spaces': 'error',
            'eol-last': 'error'
        }
    }
];